# Generated by Django 3.0.14 on 2024-01-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagepost',
            old_name='posts',
            new_name='post',
        ),
    ]
