# Generated by Django 4.2.5 on 2023-11-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc',
            name='email1',
            field=models.EmailField(default='a', max_length=254),
            preserve_default=False,
        ),
    ]
