# Generated by Django 3.0.14 on 2023-12-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20231206_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abc',
        ),
    ]
