# Generated by Django 3.0.14 on 2024-01-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abc',
        ),
    ]
