# Generated by Django 4.2.5 on 2023-12-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postaction',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postviewed',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postviewed',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostAction',
        ),
        migrations.DeleteModel(
            name='PostViewed',
        ),
    ]
