# Generated by Django 4.2.5 on 2023-12-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaction',
            name='net',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
