# Generated by Django 4.2.5 on 2023-12-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_postaction_net'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postaction',
            name='net',
        ),
    ]
