# Generated by Django 3.0.14 on 2024-03-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20240123_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
